services:
  pixart-api:
    container_name: pixart-api
    image: realpha39/pixart-ollama
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Expose API on port 8000
    environment:
      - MODEL_PATH=/app  # Path to the models in the host machine
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    networks:
      - shared-network

  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - "11434:11434"  # Default port for Ollama
    command: >
      /bin/bash -c "ollama serve & sleep 5 && ollama pull gemma2:2b"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    networks:
      - shared-network

networks:
  shared-network:
    driver: bridge
