services:
  pixart-api:
    container_name: pixart-api
    image: realpha39/pixart-ollama
    build:
      context: .
      dockerfile: pixart.dockerfile
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    networks:
      - shared-network

  ollama:
    container_name: ollama
    build:
      context: .
      dockerfile: ollama.dockerfile
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    networks:
      - shared-network
networks:
  shared-network:
    driver: bridge
