name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - uses: actions/checkout@v4

    # Step 2: Set up Docker Compose
    - name: Set up Docker Compose
      run: sudo apt-get install docker-compose

    # Step 3: Build and start Docker Compose services
    - name: Build and run Docker Compose
      run: docker-compose up --build -d --tag my-image-name:$(date +%s)

